USE MASTER
-- DROP DATABASE QLBH2019;
-- CREATE DATABASE QLBH2019;
USE qlbh2019;

CREATE TABLE NHANVIEN
(
	MANHANVIEN CHAR(10) NOT NULL PRIMARY KEY, -- PK
    HOTEN NVARCHAR(255),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(50),
    DIENTHOAI VARCHAR(15),
    LUONGCOBAN MONEY CONSTRAINT CHK_LUONG CHECK(LUONGCOBAN>0),
    PHUCAP MONEY CONSTRAINT CHK_MUCPHUCAP CHECK(PHUCAP>=0)
);

CREATE TABLE KHACHHANG
(
	MAKHACHHANG CHAR(10) PRIMARY KEY NOT NULL, -- PK
    HOTEN NVARCHAR(50),
    DIACHI NVARCHAR(50),
    DIENTHOAI VARCHAR(15),
    FAX VARCHAR(15),
	EMAIL VARCHAR(255)
);

CREATE TABLE LOAIHANG
(
	MALOAIHANG CHAR(10) PRIMARY KEY NOT NULL,
    TENLOAIHANG NVARCHAR(255)
);

CREATE TABLE MATHANG
(
	MAHANG CHAR(10) PRIMARY KEY NOT NULL, -- PK
    TENHANG NVARCHAR(255),
    MALOAIHANG CHAR(10) NOT NULL, -- FK
    SOLUONG INT 
		CONSTRAINT CHK_SOLUONG CHECK(SOLUONG>0),

    DONVITINH NVARCHAR(25),
    GIAHANG MONEY
		CONSTRAINT CHK_GIAHANG CHECK(GIAHANG>0)
);

CREATE TABLE DONDATHANG
(
	SOHOADON INT NOT NULL PRIMARY KEY, -- PK
    MAKHACHHANG CHAR(10) NOT NULL, -- FK 
    MANHANVIEN CHAR(10) NOT NULL, -- FK
    NGAYDATHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(50)
);

CREATE TABLE CHITIETDATHANG
(
	SOHOADON INT NOT NULL, -- PK
    MAHANG CHAR(10) NOT NULL, -- PK
    GIABAN MONEY
		CONSTRAINT CHK_GIABAN CHECK(GIABAN>0),
    SOLUONG INT CONSTRAINT CHK_SOLUONG_1 CHECK(SOLUONG>0),
    MUCGIAMGIA INT
);

ALTER TABLE CHITIETDATHANG ADD CONSTRAINT PK_CTDH PRIMARY KEY (SOHOADON, MAHANG);

ALTER TABLE DONDATHANG ADD CONSTRAINT FK_DDH_MAKH FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE DONDATHANG ADD CONSTRAINT FK_DDH_NANV FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE MATHANG ADD CONSTRAINT FK_MAHANG_MALH FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG) ON UPDATE CASCADE ON DELETE CASCADE;
