DROP TABLE IF EXISTS LS_THAY_DOI;
DROP TRIGGER IF EXISTS INS_CN;
DROP TRIGGER IF EXISTS DEL_CN;
DROP TRIGGER IF EXISTS UPDATE_CN;
DROP TRIGGER IF EXISTS INS_NVDT;
DROP TRIGGER IF EXISTS DEL_NVDT;
DROP TRIGGER IF EXISTS UPDATE_NVDT;
DROP TRIGGER IF EXISTS INS_NV;
DROP TRIGGER IF EXISTS DEL_NV;
DROP TRIGGER IF EXISTS UPDATE_NV;

 CREATE TABLE LS_THAY_DOI
(
	LOAI_THAY_DOI VARCHAR(50),
	NGAY_THAY_DOI DATE,
    GIO_THAY_DOI TIME,
    MANV NVARCHAR(11),
    HOTEN NVARCHAR(100),
    MAPB CHAR(3),
    NGAYSINH DATE,
    MATINH TINYINT,
    GIOITINH NVARCHAR(5),
    GHICHU NVARCHAR(50),
    CONGVIEC NVARCHAR(100),
    LUONG INT
) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
 
 DELIMITER //
 CREATE TRIGGER INS_CN
 AFTER INSERT ON CONGNHAN
 FOR EACH ROW
 BEGIN
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, HOTEN, NGAYSINH, MATINH, GIOITINH, GHICHU)
					 VALUES("INSERT CONG NHAN", SYSDATE(), TIME(NOW()), NEW.MACN, NEW.HOTEN, NEW.NGAYSINH, NEW.MATINH, NEW.GIOITINH, NEW.GHICHU);
END//

CREATE TRIGGER DEL_CN
BEFORE DELETE ON CONGNHAN
FOR EACH ROW
BEGIN 
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, HOTEN, NGAYSINH, MATINH, GIOITINH, GHICHU)
	VALUES("DELETE CONG NHAN", SYSDATE(), TIME(NOW()), OLD.MACN, OLD.HOTEN, OLD.NGAYSINH, OLD.MATINH, OLD.GIOITINH, OLD.GHICHU);
END//

CREATE TRIGGER UPDATE_CN
AFTER UPDATE ON CONGNHAN
FOR EACH ROW
BEGIN 
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, HOTEN, NGAYSINH, MATINH, GIOITINH, GHICHU)
	VALUES("BEFORE UPDATE CONG NHAN", SYSDATE(), TIME(NOW()), OLD.MACN, OLD.HOTEN, OLD.NGAYSINH, OLD.MATINH, OLD.GIOITINH, OLD.GHICHU),
		  ("AFTER UPDATE CONG NHAN", SYSDATE(), TIME(NOW()), NEW.MACN, NEW.HOTEN, NEW.NGAYSINH, NEW.MATINH, NEW.GIOITINH, NEW.GHICHU);
END//

CREATE TRIGGER INS_NVDT
AFTER INSERT ON NHANVIENDACTHU
FOR EACH ROW 
BEGIN
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, HOTEN, NGAYSINH, CONGVIEC, MATINH, GIOITINH, LUONG)
				VALUES("INSERT NHANVIENDACTHU", SYSDATE(), TIME(NOW()), NEW.MANV, NEW.HOTEN, NEW.NGAYSINH, NEW.CONGVIEC, NEW.MATINH, NEW.GIOITINH, NEW.LUONG);
END//

CREATE TRIGGER DEL_NVDT
BEFORE DELETE ON NHANVIENDACTHU
FOR EACH ROW
BEGIN
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, HOTEN, NGAYSINH, CONGVIEC, MATINH, GIOITINH, LUONG)
				VALUES("DELETE NHANVIENDACTHU", SYSDATE(), TIME(NOW()), OLD.MANV, OLD.HOTEN, OLD.NGAYSINH, OLD.CONGVIEC, OLD.MATINH, OLD.GIOITINH, OLD.LUONG);
END//

CREATE TRIGGER UPDATE_NVDT
AFTER UPDATE ON NHANVIENDACTHU
FOR EACH ROW
BEGIN
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, HOTEN, NGAYSINH, CONGVIEC, MATINH, GIOITINH, LUONG)
				VALUES("BEFORE UPDATE NHANVIENDACTHU", SYSDATE(), TIME(NOW()), OLD.MANV, OLD.HOTEN, OLD.NGAYSINH, OLD.CONGVIEC, OLD.MATINH, OLD.GIOITINH, OLD.LUONG),
					  ("AFTER UPDATE NHANVIENDACTHU", SYSDATE(), TIME(NOW()), NEW.MANV, NEW.HOTEN, NEW.NGAYSINH, NEW.CONGVIEC, NEW.MATINH, NEW.GIOITINH, NEW.LUONG);
END//

CREATE TRIGGER INS_NV
AFTER INSERT ON NHANVIEN
FOR EACH ROW
BEGIN 
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, MAPB, HOTEN, NGAYSINH, GIOITINH, MATINH, CONGVIEC, LUONG)
				VALUES("INSERT NHANVIEN",SYSDATE(), TIME(NOW()), NEW.MANV, NEW.MAPB, NEW.HOTEN, NEW.NGAYSINH, NEW.GIOITINH, NEW.MATINH, NEW.CONGVIEC, NEW.LUONG);
END//

CREATE TRIGGER DEL_NV
BEFORE DELETE ON NHANVIEN
FOR EACH ROW
BEGIN 
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, MAPB, HOTEN, NGAYSINH, GIOITINH, MATINH, CONGVIEC, LUONG)
				VALUES("DELETE NHANVIEN",SYSDATE(), TIME(NOW()), OLD.MANV, OLD.MAPB, OLD.HOTEN, OLD.NGAYSINH, OLD.GIOITINH, OLD.MATINH, OLD.CONGVIEC, OLD.LUONG);
END//
 
CREATE TRIGGER UPDATE_NV
AFTER UPDATE ON NHANVIEN
FOR EACH ROW
BEGIN 
	INSERT INTO LS_THAY_DOI(LOAI_THAY_DOI, NGAY_THAY_DOI, GIO_THAY_DOI, MANV, MAPB, HOTEN, NGAYSINH, GIOITINH, MATINH, CONGVIEC, LUONG)
				VALUES("BEFORE UPDATE NHANVIEN",SYSDATE(), TIME(NOW()), OLD.MANV, OLD.MAPB, OLD.HOTEN, OLD.NGAYSINH, OLD.GIOITINH, OLD.MATINH, OLD.CONGVIEC, OLD.LUONG),
					  ("AFTER UPDATE NHANVIEN",SYSDATE(), TIME(NOW()), NEW.MANV, NEW.MAPB, NEW.HOTEN, NEW.NGAYSINH, NEW.GIOITINH, NEW.MATINH, NEW.CONGVIEC, NEW.LUONG);
END//
 
 
 
 